# -*- coding: utf-8 -*-
"""Assignment - AI/Ml.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AUTrBO00F5g-nrSx044Z6pXxDbpcjwt8
"""

pip install transformers

pip install torch

pip install sentencepiece

import torch
from transformers import MarianTokenizer, MarianMTModel

def hinglish_translation(input_text):
    # Load the Marian NMT model for English to Hindi translation
    model_name = "Helsinki-NLP/opus-mt-en-hi"
    tokenizer = MarianTokenizer.from_pretrained(model_name)
    model = MarianMTModel.from_pretrained(model_name)

    # Tokenize and translate the input English text to Hindi
    input_ids = tokenizer.encode(input_text, return_tensors="pt")
    translated_ids = model.generate(input_ids, max_length=50, num_beams=5, early_stopping=True)
    translated_text = tokenizer.decode(translated_ids[0], skip_special_tokens=True)

    return translated_text

english_text = input()
hinglish_output = hinglish_translation(english_text)
print("Input English Text:",english_text)
print("Hinglish Translation:",hinglish_output)

english_text = input()
hinglish_output = hinglish_translation(english_text)
print("Input English Text:",english_text)
print("Hinglish Translation:",hinglish_output)

english_text = input()
hinglish_output = hinglish_translation(english_text)
print("Input English Text:",english_text)
print("Hinglish Translation:",hinglish_output)

